### PR TITLE
Add HashMap in-memory index for FlyDB(#99)

### PR DESCRIPTION
**Pull request by lim-yoona**
## Description
I add a new in-memory index, HashMap, for FlyDB

## Issue
#99

### CODE REVIEW

**Comment by qishenonly** [comment]
Thank you for your pr. Your code has an initialization slicing problem that could result in null values, and a small error in testing the initialization iterator.   In addition, note that the annatations should be written in English.   Remember to revise in time.
We will merge your pr onto the master branch after we review it again and pass the ci.

**Comment by lim-yoona** [comment]
Thank you for your review. I have revised my code to avoid creating a nil slice values, and I have rewrited the annatations in English. Is there any other problems about my code?

**Comment by qishenonly** [comment]
> Thank you for your review. I have revised my code to avoid creating a nil slice values, and I have rewrited the annatations in English. Is there any other problems about my code?谢谢您，对于您的评论。我修改了代码以避免创建 nil 切片值，并且用英语重写了注释。我的代码还有其他问题吗？

image
In the retest case, `NewHashMap` is used instead of `NewBtree`

**Comment by lim-yoona** [comment]
> > Thank you for your review. I have revised my code to avoid creating a nil slice values, and I have rewrited the annatations in English. Is there any other problems about my code?
> 
> image In the retest case, `NewHashMap` is used instead of `NewBtree`

Oh, sorry, I will solve it.

**Comment by lim-yoona** [comment]
I think I have solved the problem, Is there any other problems about my code?

**Comment by qishenonly** [comment]
> I think I have solved the problem, Is there any other problems about my code?

no problems,thanks.

**Pull request merged**
