### PR TITLE
add `gofmt` to GitHub actions (#161)

### PR DESCRIPTION
**Pull request by saeid-a**

### CODE REVIEW

**Comment by sjcsjc123** [comment]
Can golangci-lint static analysis tools also be added? You can visit https://github.com/golangci/golangci-lint

**Comment by saeid-a** [comment]
> 

@sjcsjc123 Done. Adding other jobs to the pipeline might also be a good idea.

**Comment by sjcsjc123** [comment]
Yes, if there are suitable jobs, you can add them.

**Comment by saeid-a** [comment]
@sjcsjc123 sure, i will add them in a separate PR.

**Review by sjcsjc123 — APPROVED** [review]

**Pull request merged**
