### PR TITLE
I modified the Logo to make it more three-dimensional

### PR DESCRIPTION
**Pull request by lim-yoona**
## description
The new Logo style is like this:  
image

## related issue
#228

### CODE REVIEW

**Comment by sjcsjc123** [comment]
Thanks. I think it likes very good!

**Review by sjcsjc123 — DISMISSED** [review]

**Comment by qishenonly** [comment]
The second letter looks like an I. Can you make it look like a capital L.

**Comment by lim-yoona** [comment]
> The second letter looks like an I. Can you make it look like a capital L.

Yes, I can. And i think making both 'i' and 'y' uppercase would be more aesthetically pleasing.

**Comment by qishenonly** [comment]
> > The second letter looks like an I. Can you make it look like a capital L
> 
> Yes, I can. And i think making both 'i' and 'y' uppercase would be more aesthetically pleasing.

Good idea！

**Comment by lim-yoona** [comment]
I changed 'i' to 'L' and tried changing 'y' to 'Y' but it was too difficult so I kept the letter y
This is the effect:
image

**Comment by peng-yq** [comment]
> I changed 'i' to 'L' and tried changing 'y' to 'Y' but it was too difficult so I kept the letter y This is the effect: image

I think it may look better if below of FLYDB is on the same line like *FLYDB*， u can make "F" larger :)

**Review by qishenonly — APPROVED** [review]

**Pull request merged**
