### PR TITLE
Implement all functions of ListStructure(#137 ID 1~13)

### PR DESCRIPTION
**Pull request by SandTripper**

### CODE REVIEW

**Comment by qishenonly** [comment]
Your development efficiency looks pretty good.   I have reviewed your code, there is an error and an unreasonable place in the code, please modify it in time.   After the newly modified commit passes the ci, I will merge it into the main branch.

**Comment by SandTripper** [comment]
> 看来你的开发效率还不错。我已经检查了您的代码，代码中存在错误和不合理的地方，请及时修改。新修改的commit通过ci后，我会将其合并到主分支中。

我已经修改了编译出错的地方，并合并成了一个commit

**Comment by SandTripper** [comment]
> Your development efficiency looks pretty good. I have reviewed your code, there is an error and an unreasonable place in the code, please modify it in time. After the newly modified commit passes the ci, I will merge it into the main branch.
I have fixed the compilation error and merged it into a commit

**Comment by SandTripper** [comment]
> Your development efficiency looks pretty good. I have reviewed your code, there is an error and an unreasonable place in the code, please modify it in time. After the newly modified commit passes the ci, I will merge it into the main branch.

I have fixed the compilation error and merged it into a commit

**Comment by qishenonly** [comment]
> 

Thank you for your contributions.

**Pull request merged**
